# Generated by Django 4.2 on 2026-06-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0004_workshop_pos_modules"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompliancePeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_label", models.CharField(max_length=7, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active (Collecting)"),
                            ("staging", "Staging (Under Review)"),
                            ("finalized", "Finalized / Locked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "field1_standard_rated_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "field4_output_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "field14_capital_goods_input",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "field15_non_capital_input",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_vat_liability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_uif_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_uif_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("audit_flags", models.JSONField(blank=True, default=list)),
                ("audit_ready", models.BooleanField(default=False)),
                ("audit_zip_path", models.CharField(blank=True, max_length=500)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_periods",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_number", models.CharField(max_length=20, unique=True)),
                ("id_number", models.CharField(blank=True, max_length=13)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("tax_reference_number", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=30)),
                ("bank_branch_code", models.CharField(blank=True, max_length=10)),
                ("physical_address", models.TextField(blank=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("next_of_kin_name", models.CharField(blank=True, max_length=200)),
                ("next_of_kin_contact", models.CharField(blank=True, max_length=20)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time Permanent"),
                            ("part_time", "Part-Time"),
                            ("contract", "Fixed-Term Contract"),
                            ("hourly", "Hourly / Casual"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "gross_monthly_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "scheduled_hours_per_week",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "HQ Administrator"),
                            ("agent", "Support Agent"),
                            ("finance", "Finance/Billing"),
                            ("cashier", "Administrative Desk / Cashier"),
                            ("technician", "Service Technician"),
                            ("client", "Client User"),
                            ("viewer", "Viewer (Read-only)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily_morning", "Daily — Morning Routine"),
                            ("daily_evening", "Daily — Evening Routine"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("link_url", models.CharField(blank=True, max_length=300)),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="If True, user cannot proceed past this task (e.g. shift open float).",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "task_templates",
                "ordering": ["frequency", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SupplierSlipOCR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_vat_number", models.CharField(blank=True, max_length=15)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stated_vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_capital_goods", models.BooleanField(default=False)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("valid", "Valid"),
                            ("invalid", "Incomplete / Audit Risk"),
                            ("manual", "Manually Verified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ocr_flags", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compliance_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_slips",
                        to="ims.complianceperiod",
                    ),
                ),
                (
                    "purchase_slip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_record",
                        to="ims.purchaseslip",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_slips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supplier_slip_ocr",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("family", "Family Responsibility Leave"),
                            ("maternity", "Maternity / Paternity Leave"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_requested", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="ims.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_ref", models.DateField(db_index=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "completed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="ims.tasktemplate",
                    ),
                ),
            ],
            options={
                "db_table": "task_completions",
                "ordering": ["-completed_at"],
                "unique_together": {("task_template", "completed_by", "date_ref")},
            },
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "regular_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paye_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("uif_employee", models.DecimalField(decimal_places=2, max_digits=8)),
                ("uif_employer", models.DecimalField(decimal_places=2, max_digits=8)),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_frozen", models.BooleanField(default=False)),
                ("payslip_emailed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_entries",
                        to="ims.complianceperiod",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_entries",
                        to="ims.employee",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_entries",
                "ordering": ["-compliance_period__period_start", "employee__last_name"],
                "unique_together": {("employee", "compliance_period")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("family", "Family Responsibility Leave"),
                            ("maternity", "Maternity / Paternity Leave"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("cycle_start", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="ims.employee",
                    ),
                ),
            ],
            options={
                "db_table": "leave_balances",
                "unique_together": {("employee", "leave_type", "cycle_start")},
            },
        ),
    ]
