# Generated by Django 4.2 on 2026-06-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0005_sars_compliance_hr_playbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("it_support", "IT Support"),
                            ("networking", "Networking"),
                            ("cctv", "CCTV & Security"),
                            ("software", "Software"),
                            ("hardware", "Hardware"),
                            ("cloud", "Cloud Services"),
                            ("other", "Other"),
                        ],
                        default="it_support",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        default="per visit",
                        help_text="e.g. per device, per month, per hour",
                        max_length=60,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on website hero/pricing section"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_prices",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("about", "About Us"),
                            ("services", "Services Section"),
                            ("process", "How It Works"),
                            ("cta", "Call To Action"),
                            ("contact", "Contact Info"),
                            ("footer", "Footer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label shown in HQ editor",
                        max_length=120,
                    ),
                ),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "website_content",
                "ordering": ["section", "key"],
            },
        ),
    ]
