# Generated by Django 4.2 on 2026-07-04 16:04 (hand-trimmed: dropped unrelated
# field-drift alterations to companysettings/revenueallocation/slacontract/
# wifisubscriber that auto-detect differently across environments and are not
# part of this migration's actual change set).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0010_company_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "system_key",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=10,
                    ),
                ),
                ("account_subtype", models.CharField(blank=True, max_length=30)),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="cashtransaction",
            name="transaction_category",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("capital_injection", "Owner Capital Injection"),
                    ("owner_drawing", "Owner's Drawing"),
                    ("other", "Other"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=255)),
                ("source_model", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=50)),
                (
                    "cash_flow_stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ocf", "Operating Cash Flow"),
                            ("icf", "Investing Cash Flow"),
                            ("fcf", "Financing Cash Flow"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="ims.ledgertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="ims.account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ims.ledgertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cogs", "Cost of Goods Sold"),
                            ("operating", "Operating Expense"),
                            ("capital", "Capital / Asset Purchase"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vendor", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("expense_date", models.DateField()),
                (
                    "cash_flow_stream",
                    models.CharField(
                        choices=[
                            ("ocf", "Operating Cash Flow"),
                            ("icf", "Investing Cash Flow"),
                            ("fcf", "Financing Cash Flow"),
                        ],
                        default="ocf",
                        max_length=10,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid / Payable")],
                        default="paid",
                        max_length=10,
                    ),
                ),
                ("receipt_image_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="ims.account",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cash_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="ims.cashtransaction",
                    ),
                ),
                (
                    "purchase_slip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense",
                        to="ims.purchaseslip",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["source_model", "source_id"],
                name="ledger_tran_source__36d58d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["transaction_date"], name="ledger_tran_transac_a9cf24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["account"], name="ledger_entr_account_77a3a6_idx"
            ),
        ),
    ]
