# Generated by Django 4.2 on 2026-07-14 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0012_invoice_partial_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("wifi", "WiFi Subscription"),
                    ("sla", "SLA Monthly Retainer"),
                    ("callout", "SLA Call-Out"),
                    ("adhoc", "Ad-Hoc / Project"),
                    ("subscription", "Other Subscription (Email/Hosting/etc.)"),
                ],
                db_index=True,
                default="adhoc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Hosting"),
                            ("hosting", "Website Hosting"),
                            ("domain", "Domain Registration"),
                            ("backup", "Cloud Backup"),
                            ("software", "Software License"),
                            ("other", "Other Subscription"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Microsoft 365 Business Basic", "cPanel hosting — rehumile.co.za"',
                        max_length=255,
                    ),
                ),
                ("client_name", models.CharField(db_index=True, max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What you charge the client per month",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What the supplier charges you per month (0 if none)",
                        max_digits=10,
                    ),
                ),
                (
                    "billing_day",
                    models.IntegerField(
                        default=1, help_text="Day of month invoice is generated"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="ims.company",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["client_name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="ims.subscription",
            ),
        ),
    ]
