# Generated by Django 4.2 on 2026-07-14 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0013_subscription_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "FNB Business — July 2026"', max_length=200
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_statements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_date", models.DateField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched Automatically"),
                            ("manual", "Matched Manually"),
                            ("unmatched", "Unmatched"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_lines",
                        to="ims.ledgerentry",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ims.bankstatement",
                    ),
                ),
            ],
            options={
                "db_table": "bank_statement_lines",
                "ordering": ["line_date", "created_at"],
            },
        ),
    ]
