# Generated by Django 4.2 on 2026-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0014_remove_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="accepted_by_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="quotation",
            name="decided_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="decision_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="first_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="public_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
