# Generated by Django 4.2 on 2026-09-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0014_bank_reconciliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cogs", "Cost of Goods Sold"),
                            ("operating", "Operating Expense"),
                            ("capital", "Capital / Asset Purchase"),
                        ],
                        default="operating",
                        max_length=12,
                    ),
                ),
                (
                    "default_cash_flow_stream",
                    models.CharField(
                        choices=[
                            ("ocf", "Operating Cash Flow"),
                            ("icf", "Investing Cash Flow"),
                            ("fcf", "Financing Cash Flow"),
                        ],
                        default="ocf",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Optional. 0 = no budget. Shown against actual spend on the Expenses page.",
                        max_digits=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_categories",
                        to="ims.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "expense categories",
                "db_table": "expense_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_phone", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("invoiced", "Invoiced"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent, e.g. 15",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="ims.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quotation",
                        to="ims.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "quotations",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="companysettings",
            name="payroll_sdl_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Charge the 1% Skills Development Levy on payroll. Employers with an annual payroll under R500,000 are exempt.",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed taxable allowance paid every month (transport, phone, ...).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_other_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed after-tax deduction every month (staff loan repayment, garnishee, ...).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="allowances",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="other_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="sdl_employer",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="serviceprice",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardware", "Hardware & Support"),
                    ("software", "Software Products"),
                    ("pos", "Point of Sale"),
                    ("combo", "Combos & Value Packages"),
                ],
                db_index=True,
                help_text="Pricing card on the website this item appears in.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceprice",
            name="price_prefix",
            field=models.CharField(
                blank=True,
                help_text='e.g. "From" — shown before the price on the website',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected cost to Rehumile per unit (parts, wholesale, labour) — internal only.",
                        max_digits=12,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "cost_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_items",
                        to="ims.expensecategory",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ims.quotation",
                    ),
                ),
                (
                    "service_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_items",
                        to="ims.serviceprice",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_items",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="ims.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="ims.quotation",
            ),
        ),
    ]
