# Generated by Django 4.2 on 2026-09-30 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0015_quotation_online_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bill_to_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("wifi", "WiFi Subscription"),
                    ("sla", "SLA Monthly Retainer"),
                    ("callout", "SLA Call-Out"),
                    ("adhoc", "Ad-Hoc / Project"),
                    ("subscription", "Monthly Services (combined)"),
                ],
                db_index=True,
                default="adhoc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "Jozini Branch"', max_length=200),
                ),
                ("address", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("head_office", "Billed to head office"),
                            ("self", "Branch pays its own invoice"),
                        ],
                        default="head_office",
                        help_text="Head office: this branch's services appear on the head office invoice. Branch pays: it gets its own invoice.",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="ims.company",
                    ),
                ),
            ],
            options={
                "db_table": "client_sites",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="service_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="site_name",
            field=models.CharField(
                blank=True,
                help_text="Branch this line is for (shown as a heading on the invoice)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("wifi", "WiFi / Internet"),
                            ("email", "Email hosting"),
                            ("hosting", "Website hosting"),
                            ("sla", "SLA retainer"),
                            ("other", "Other service"),
                        ],
                        db_index=True,
                        default="wifi",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='Shown on the invoice, e.g. "20Mbps fibre" or "domain + 5 mailboxes"',
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the client pays per unit per month",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What it costs you per unit per month",
                        max_digits=12,
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Invoice is due on this day of the month"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("axxess_id", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="ims.company",
                    ),
                ),
                (
                    "legacy_sla",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="ims.slacontract",
                    ),
                ),
                (
                    "legacy_wifi",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="ims.wifisubscriber",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="ims.clientsite",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": [
                    "company__name",
                    "client_name",
                    "site__name",
                    "service_type",
                ],
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="ims.subscription",
            ),
        ),
    ]
