# Generated by Django 4.2 on 2026-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0016_seed_defaults_backfill_dates"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Voucher",
        ),
    ]
