# Generated by Django 4.2 on 2026-09-30 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0017_import_legacy_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_notice_at",
            field=models.DateTimeField(
                blank=True,
                help_text='The client used "I have paid" on their invoice page',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_notice_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invoice",
            name="public_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reminder_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Axxess office fibre", "rehumile.co.za domain"',
                        max_length=150,
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Every 3 months"),
                            ("annual", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Posts on this day (short months use the last day)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid / Payable")],
                        default="paid",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_posted_for", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_expenses",
                        to="ims.expensecategory",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_expenses",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="ims.recurringexpense",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expense",
            unique_together={("recurring_source", "occurrence_date")},
        ),
    ]
