# Generated by Django 4.2 on 2026-09-30 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


# Service types the old Subscription model allowed that the new one folds into "other"
_FOLDED = {"domain": "Domain registration", "backup": "Cloud backup", "software": "Software license"}
_LABELS = {"email": "Email hosting", "hosting": "Website hosting", "other": "Other service"}


def convert_existing_subscriptions(apps, schema_editor):
    """Keep every existing subscription: name goes into the description, the contact name into notes."""
    Subscription = apps.get_model("ims", "Subscription")
    for sub in Subscription.objects.all():
        old_type = sub.service_type
        label = _FOLDED.get(old_type) or _LABELS.get(old_type, "Other service")
        name = (sub.service_name or "").strip()
        sub.description = (f"{label} — {name}" if name and name.lower() != label.lower() else (name or label))[:255]
        if old_type in _FOLDED:
            sub.service_type = "other"
        if sub.contact_name:
            sub.notes = (f"Contact: {sub.contact_name}\n" + (sub.notes or "")).strip()
        if sub.start_date is None:
            sub.start_date = sub.created_at.date()
        sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0018_quotation_online_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bill_to_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("wifi", "WiFi Subscription"),
                    ("sla", "SLA Monthly Retainer"),
                    ("callout", "SLA Call-Out"),
                    ("adhoc", "Ad-Hoc / Project"),
                    ("subscription", "Monthly Services (combined)"),
                ],
                db_index=True,
                default="adhoc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "Jozini Branch"', max_length=200),
                ),
                ("address", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("head_office", "Billed to head office"),
                            ("self", "Branch pays its own invoice"),
                        ],
                        default="head_office",
                        help_text="Head office: this branch's services appear on the head office invoice. Branch pays: it gets its own invoice.",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="ims.company",
                    ),
                ),
            ],
            options={
                "db_table": "client_sites",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="service_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="site_name",
            field=models.CharField(
                blank=True,
                help_text="Branch this line is for (shown as a heading on the invoice)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        # The live database already has a `subscriptions` table (created by 0013_subscription_model).
        # Convert it in place so existing rows survive, instead of creating a second table.
        migrations.RenameField("subscription", "subscription_type", "service_type"),
        migrations.RenameField("subscription", "monthly_price", "unit_price"),
        migrations.RenameField("subscription", "monthly_cost", "unit_cost"),
        migrations.AddField(
            model_name="subscription", name="description",
            field=models.CharField(blank=True, default="", max_length=255,
                                   help_text='Shown on the invoice, e.g. "20Mbps fibre" or "domain + 5 mailboxes"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription", name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name="subscription", name="axxess_id",
            field=models.CharField(blank=True, default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription", name="site",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name="subscriptions", to="ims.clientsite"),
        ),
        migrations.AddField(
            model_name="subscription", name="legacy_sla",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name="subscription", to="ims.slacontract"),
        ),
        migrations.AddField(
            model_name="subscription", name="legacy_wifi",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name="subscription", to="ims.wifisubscriber"),
        ),
        migrations.RunPython(convert_existing_subscriptions, migrations.RunPython.noop),
        migrations.RemoveField("subscription", "service_name"),
        migrations.RemoveField("subscription", "contact_name"),
        migrations.AlterField(
            model_name="subscription", name="service_type",
            field=models.CharField(
                choices=[("wifi", "WiFi / Internet"), ("email", "Email hosting"), ("hosting", "Website hosting"),
                         ("sla", "SLA retainer"), ("other", "Other service")],
                db_index=True, default="wifi", max_length=20),
        ),
        migrations.AlterField(
            model_name="subscription", name="client_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="subscription", name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="subscription", name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12,
                                      help_text="What the client pays per unit per month"),
        ),
        migrations.AlterField(
            model_name="subscription", name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12,
                                      help_text="What it costs you per unit per month"),
        ),
        migrations.AlterField(
            model_name="subscription", name="billing_day",
            field=models.PositiveSmallIntegerField(default=1, help_text="Invoice is due on this day of the month"),
        ),
        migrations.AlterField(
            model_name="subscription", name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="subscription", name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name="subscriptions", to="ims.company"),
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["company__name", "client_name", "site__name", "service_type"]},
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="ims.subscription",
            ),
        ),
    ]
