# Generated by Django 4.2 on 2026-10-02 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0023_subscription_invoice_separately_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier", models.CharField(default="Axxess", max_length=100)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Thebado & Maputaland FM"',
                        max_length=200,
                    ),
                ),
                (
                    "charged_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What the supplier charges on this account per month, from their latest invoice",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "supplier_accounts",
                "ordering": ["supplier", "account_number"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="is_supplier_bill",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ExpenseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ims.expense",
                    ),
                ),
                (
                    "recurring_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_lines",
                        to="ims.recurringexpense",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_lines",
                        to="ims.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "expense_lines",
                "ordering": ["description"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="supplier_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="ims.supplieraccount",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="supplier_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="own_lines",
                to="ims.supplieraccount",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="supplier_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_lines",
                to="ims.supplieraccount",
            ),
        ),
    ]
