# Generated by Django 4.2 on 2026-10-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0025_seed_axxess_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_expenses",
                to="ims.invoice",
            ),
        ),
    ]
