# Generated by Django 5.1.7 on 2026-09-19 14:28

import HR.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="hr/company/"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Employer banner shown on 'This is me'.",
                        null=True,
                        upload_to="hr/company/",
                    ),
                ),
                (
                    "primary_colour",
                    models.CharField(
                        default="#1a3a5c",
                        help_text="Hex colour, for example #1a3a5c.",
                        max_length=7,
                    ),
                ),
                ("retirement_age", models.PositiveSmallIntegerField(default=65)),
                (
                    "work_days",
                    models.CharField(
                        default="0,1,2,3,4",
                        help_text="Days of the week that are working days, as numbers (Monday=0 ... Sunday=6), comma separated.",
                        max_length=20,
                    ),
                ),
                (
                    "show_team_leave_names",
                    models.BooleanField(
                        default=True,
                        help_text="Team calendar shows who is off. When off it shows only 'unavailable'.",
                    ),
                ),
                (
                    "information_officer",
                    models.CharField(
                        blank=True,
                        help_text="POPIA Information Officer.",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CostCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centres",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="hr.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_number", models.CharField(max_length=30)),
                ("known_as", models.CharField(max_length=100)),
                ("first_names", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("X", "Other / non-binary"),
                            ("N", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "African"),
                            ("C", "Coloured"),
                            ("I", "Indian"),
                            ("W", "White"),
                            ("O", "Other"),
                            ("N", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "id_number",
                    HR.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted at rest.", null=True
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, default="South African", max_length=80
                    ),
                ),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="hr/photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On extended leave"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed term"),
                            ("CASUAL", "Casual"),
                            ("INTERN", "Intern / learnership"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr.company",
                    ),
                ),
                (
                    "cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.costcentre",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="hr.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["surname", "known_as"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Kept so the entry still reads if the login is removed.",
                        max_length=150,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("module", models.CharField(db_index=True, max_length=40)),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("sensitive", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee the entry is about, for searching.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used for employees with no policy set.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "leave policies",
                "ordering": ["company", "name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="leave_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.leavepolicy",
            ),
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(max_length=20)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "annual_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Days per year.",
                        max_digits=6,
                    ),
                ),
                (
                    "accrual_method",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Accrues monthly"),
                            ("ANNUAL", "Full entitlement credited each January"),
                            ("NONE", "No accrual (balance set by adjustment)"),
                        ],
                        default="MONTHLY",
                        max_length=8,
                    ),
                ),
                (
                    "carry_over_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Most days carried into the next year; the rest expire. Leave blank for no limit.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "allow_negative",
                    models.BooleanField(
                        default=False,
                        help_text="Allow the balance to go below zero (leave taken in advance).",
                    ),
                ),
                (
                    "max_negative_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("half_days_allowed", models.BooleanField(default=True)),
                (
                    "min_notice_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Calendar days of notice needed before the leave starts.",
                    ),
                ),
                (
                    "attachment_required_over_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="A supporting document (for example a medical certificate) is mandatory when the request is longer than this many days.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("colour", models.CharField(default="#1a3a5c", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "half_day_start",
                    models.BooleanField(
                        default=False, help_text="Only the afternoon of the first day."
                    ),
                ),
                (
                    "half_day_end",
                    models.BooleanField(
                        default=False, help_text="Only the morning of the last day."
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Working days, calculated.",
                        max_digits=6,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="hr/leave/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                            ("CANCEL_REQUESTED", "Cancellation requested"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "pending_action",
                    models.CharField(
                        default="APPLY",
                        help_text="APPLY for a new request, CANCEL while a cancellation awaits approval.",
                        max_length=6,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when HR captured the request on the employee's behalf.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="leave_types",
            field=models.ManyToManyField(
                blank=True, related_name="policies", to="hr.leavetype"
            ),
        ),
        migrations.CreateModel(
            name="BlackoutPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_periods",
                        to="hr.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for everyone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.department",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for every leave type.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Approval needed"),
                            ("DECISION", "Request decided"),
                            ("OVERDUE", "Approval overdue"),
                            ("PAYSLIP", "Payslip / tax certificate"),
                            ("ROSTER", "Roster"),
                            ("DOCUMENT", "Documents"),
                            ("CASE", "Employee relations"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("emailed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="hr.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "title"],
                "unique_together": {("company", "title")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.position",
            ),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="EmploymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed term"),
                            ("CASUAL", "Casual"),
                            ("INTERN", "Intern / learnership"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[("SALARIED", "Salaried"), ("HOURLY", "Hourly")],
                        default="SALARIED",
                        max_length=10,
                    ),
                ),
                (
                    "salary_amount",
                    HR.fields.EncryptedDecimalField(
                        blank=True,
                        help_text="Monthly salary or hourly rate. Encrypted at rest.",
                        null=True,
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("HIRE", "Hire"),
                            ("PROMOTION", "Promotion"),
                            ("TRANSFER", "Transfer"),
                            ("PAY_CHANGE", "Pay change"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.costcentre",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="hr.employee",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.position",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.site",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30)),
                ("object_id", models.PositiveBigIntegerField()),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hr.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee the request is for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("LINE_MANAGER", "Line Manager"),
                            ("HR_ADMIN", "HR Admin"),
                            ("PAYROLL_ADMIN", "Payroll Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting for earlier step"),
                            ("PENDING", "Awaiting decision"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="A named approver (for example the line manager). Empty means anyone holding the role.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="hr.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["instance", "order"],
            },
        ),
        migrations.CreateModel(
            name="LeaveTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACCRUAL", "Accrual"),
                            ("USAGE", "Leave taken"),
                            ("RESTORE", "Leave cancelled (restored)"),
                            ("ADJUSTMENT", "Manual adjustment"),
                            ("EXPIRY", "Expired at year end"),
                            ("OPENING", "Opening balance"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Positive adds to the balance, negative takes from it.",
                        max_digits=7,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "period_key",
                    models.CharField(
                        blank=True,
                        help_text="Makes a scheduled accrual run once per period, e.g. 2026-09.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_transactions",
                        to="hr.employee",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="hr.leaverequest",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "leave_type"],
                        name="hr_leavetra_employe_efda83_idx",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="leavepolicy",
            unique_together={("company", "name")},
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("LINE_MANAGER", "Line Manager"),
                            ("HR_ADMIN", "HR Admin"),
                            ("PAYROLL_ADMIN", "Payroll Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for all companies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "role", "company")},
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_holidays",
                        to="hr.company",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for all sites.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.site",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("company", "date", "site")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("company", "employee_number")},
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("leave", "Leave request"),
                            ("change_standard", "Profile change"),
                            ("change_banking", "Banking change"),
                            ("payrun_input", "Payrun input"),
                            ("document_request", "Document request"),
                            ("shift_change", "Shift change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text='Approval roles in order, e.g. ["LINE_MANAGER", "HR_ADMIN"].',
                    ),
                ),
                (
                    "escalation_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Working days before a reminder, then escalation to HR.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "key"],
                "unique_together": {("company", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="hr_workflow_content_ea0f33_idx",
            ),
        ),
    ]
