# Generated by Django 5.1.7 on 2026-09-19 15:13

import HR.fields
import HR.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="driver_licence_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="driver_licence_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_aid_number",
            field=HR.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_aid_scheme",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="permit_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=HR.storage.private_storage,
                upload_to="hr/leave/%Y/%m/",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=200)),
                ("suburb", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=60)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="South Africa", max_length=60)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=80)),
                ("account_holder", models.CharField(max_length=120)),
                ("account_number", HR.fields.EncryptedTextField()),
                ("branch_code", models.CharField(blank=True, max_length=12)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHEQUE", "Cheque / current"),
                            ("SAVINGS", "Savings"),
                            ("TRANSMISSION", "Transmission"),
                        ],
                        default="CHEQUE",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPDATE", "Change"),
                            ("ADD", "Add"),
                            ("REMOVE", "Remove"),
                        ],
                        default="UPDATE",
                        max_length=6,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Which list item, for add/remove/edit of a list section.",
                        null=True,
                    ),
                ),
                (
                    "old_payload",
                    HR.fields.EncryptedTextField(
                        blank=True,
                        help_text="JSON of the current values. Encrypted at rest (may hold banking details).",
                        null=True,
                    ),
                ),
                (
                    "new_payload",
                    HR.fields.EncryptedTextField(
                        blank=True,
                        help_text="JSON of the requested values. Encrypted at rest.",
                        null=True,
                    ),
                ),
                (
                    "proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=HR.storage.private_storage,
                        upload_to="hr/proof/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dependant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("relationship", models.CharField(max_length=60)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_beneficiary", models.BooleanField(default=False)),
                (
                    "beneficiary_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependants",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("relationship", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=30)),
                ("alt_phone", models.CharField(blank=True, max_length=30)),
                ("is_next_of_kin", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="For example 2026-09 or September 2026.",
                        max_length=40,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("FORTNIGHTLY", "Fortnightly"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("pay_date", models.DateField(blank=True, null=True)),
                (
                    "input_cutoff",
                    models.DateField(
                        blank=True,
                        help_text="Last day payrun inputs are accepted (used by Payrun Input).",
                        null=True,
                    ),
                ),
                (
                    "tax_year",
                    models.PositiveSmallIntegerField(
                        help_text="The year the tax year ends in: 1 Mar 2025 to 28 Feb 2026 is 2026."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_periods",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("company", "label")},
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAYSLIP", "Payslips"),
                            ("TAXCERT", "Tax certificates"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "cert_type",
                    models.CharField(blank=True, default="IRP5", max_length=8),
                ),
                (
                    "source_file",
                    models.FileField(
                        storage=HR.storage.private_storage,
                        upload_to="hr/batches/%Y/%m/",
                    ),
                ),
                (
                    "data_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional CSV: employee_number, gross, deductions, net.",
                        null=True,
                        storage=HR.storage.private_storage,
                        upload_to="hr/batches/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PREVIEW",
                        max_length=10,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hr.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="hr.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=HR.storage.private_storage,
                        upload_to="hr/payslips/%Y/%m/",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("SUPERSEDED", "Replaced by a corrected version"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("gross", HR.fields.EncryptedDecimalField(blank=True, null=True)),
                ("deductions", HR.fields.EncryptedDecimalField(blank=True, null=True)),
                ("net", HR.fields.EncryptedDecimalField(blank=True, null=True)),
                ("match_note", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payslips",
                        to="hr.importbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty while a page could not be matched to an employee.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="hr.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-pay_period__start_date",
                    "employee__surname",
                    "-version",
                ],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("institution", models.CharField(blank=True, max_length=150)),
                (
                    "year_obtained",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("level", models.CharField(blank=True, max_length=60)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="The year the tax year ends in."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_years",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("company", "year")},
            },
        ),
        migrations.CreateModel(
            name="TaxCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_type",
                    models.CharField(
                        choices=[("IRP5", "IRP5"), ("IT3A", "IT3(a)")],
                        default="IRP5",
                        max_length=4,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=HR.storage.private_storage, upload_to="hr/tax/%Y/"
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CORRECTION", "Correction requested"),
                            ("SUPERSEDED", "Replaced by a reissued version"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("match_note", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("correction_note", models.TextField(blank=True)),
                (
                    "correction_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="hr.importbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_certificates",
                        to="hr.employee",
                    ),
                ),
                (
                    "tax_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="hr.taxyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-tax_year__year", "employee__surname", "-version"],
            },
        ),
        migrations.AddField(
            model_name="importbatch",
            name="tax_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="hr.taxyear",
            ),
        ),
    ]
