# Generated by Django 5.1.7 on 2026-09-19 17:25

import HR.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_biographical_payroll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contract"),
                            ("OFFER", "Offer letter"),
                            ("CERT", "Certificate / letter"),
                            ("ID", "Identity / permit"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        storage=HR.storage.private_storage, upload_to="hr/docs/%Y/"
                    ),
                ),
                ("requires_signature", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_name", models.CharField(blank=True, max_length=150)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="ACTIVE", max_length=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYMENT", "Proof of employment"),
                            ("SALARY", "Salary / income letter"),
                            ("SERVICE", "Service certificate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="Who it is for, and why.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved - being prepared"),
                            ("READY", "Ready"),
                            ("REJECTED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employeedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "policies",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "file",
                    models.FileField(
                        storage=HR.storage.private_storage, upload_to="hr/policies/%Y/"
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "requires_ack",
                    models.BooleanField(
                        default=True, verbose_name="Employees must acknowledge"
                    ),
                ),
                ("change_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hr.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("policy", "version")},
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acks",
                        to="hr.employee",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="hr.policyversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("version", "employee")},
            },
        ),
    ]
