# Generated by Django 5.1.7 on 2026-09-19 17:44

import HR.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrunInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OVERTIME", "Overtime"),
                            ("ALLOWANCE", "Allowance"),
                            ("EXPENSE", "Expense claim"),
                            ("DEDUCTION", "Deduction request"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "work_date",
                    models.DateField(
                        blank=True, help_text="Date worked or spent.", null=True
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=HR.storage.private_storage,
                        upload_to="hr/receipts/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrun_inputs",
                        to="hr.employee",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs",
                        to="hr.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
