# Generated by Django 5.1.7 on 2026-09-19 18:30

import HR.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_roster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Received"),
                            ("INVESTIGATING", "Being looked into"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Shown to the employee when resolved."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievances",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrievanceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="hr.grievance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("venue", models.CharField(max_length=150)),
                ("purpose", models.CharField(max_length=200)),
                (
                    "notes_for_employee",
                    models.TextField(
                        blank=True,
                        help_text="Charges, your right to representation, documents to bring.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("HELD", "Held"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INVITED",
                        max_length=13,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-when"],
            },
        ),
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("VERBAL", "Verbal warning"),
                            ("WRITTEN", "Written warning"),
                            ("FINAL", "Final written warning"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reason", models.TextField()),
                ("issued_on", models.DateField()),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Usually 6 or 12 months after issue.",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=HR.storage.private_storage,
                        upload_to="hr/warnings/%Y/",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ack_comment",
                    models.CharField(
                        blank=True,
                        help_text="Employee's comment when acknowledging (acknowledging is not agreeing).",
                        max_length=255,
                    ),
                ),
                (
                    "appeal_status",
                    models.CharField(
                        choices=[
                            ("NONE", "No appeal"),
                            ("PENDING", "Appeal lodged"),
                            ("UPHELD", "Warning upheld"),
                            ("OVERTURNED", "Warning overturned"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("appeal_text", models.TextField(blank=True)),
                ("appeal_decision", models.TextField(blank=True)),
                ("withdrawn", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="hr.employee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on"],
            },
        ),
    ]
