# Generated by Django 5.1.7 on 2026-09-20 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "is_casual",
                    models.BooleanField(
                        default=False,
                        help_text="Called in as needed, not placed on a fixed pattern.",
                    ),
                ),
                (
                    "pattern_based",
                    models.BooleanField(
                        default=False,
                        help_text="Weekday pattern plus alternating weekends (office and senior management).",
                    ),
                ),
                (
                    "hours_30_31",
                    models.DecimalField(
                        decimal_places=1,
                        default=192,
                        help_text="Required paid hours for a month of 30 or 31 days. Leave empty on the person for none.",
                        max_digits=6,
                    ),
                ),
                (
                    "hours_february",
                    models.DecimalField(
                        decimal_places=1,
                        default=179.2,
                        help_text="Required paid hours for February (suggested 192 x days / 30).",
                        max_digits=6,
                    ),
                ),
                ("min_off_days_per_week", models.PositiveSmallIntegerField(default=1)),
                (
                    "max_consecutive_days",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Empty = company default (6).", null=True
                    ),
                ),
                (
                    "weekend_rotation_weeks",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="1 weekend in N. 2 = one weekend on, one off.",
                    ),
                ),
                (
                    "weekend_mode",
                    models.CharField(
                        choices=[
                            ("ONE_DAY", "Weekend duty of one day only"),
                            ("LIEU", "Day off in lieu"),
                            ("APPROVED", "Approved group rule (7 days allowed)"),
                        ],
                        default="ONE_DAY",
                        max_length=10,
                    ),
                ),
                (
                    "weekend_days",
                    models.CharField(
                        default="5",
                        help_text="Weekend days worked: 5=Saturday, 6=Sunday, comma separated.",
                        max_length=10,
                    ),
                ),
                (
                    "min_on_duty_per_weekend",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="availability",
            name="from_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="availability",
            name="to_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="night_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shift",
            name="paid_hours",
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AddField(
            model_name="shift",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shift",
            name="required",
            field=models.BooleanField(
                default=True, help_text="Counts toward the minimum cover."
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="slot_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shift",
            name="source",
            field=models.CharField(
                choices=[
                    ("GENERATED", "Generated"),
                    ("MANUAL", "Manager"),
                    ("PATTERN", "Pattern"),
                    ("CASUAL", "Casual call-out"),
                    ("SWAP", "Swap"),
                    ("EMERGENCY", "Emergency cover"),
                    ("OPEN", "Open shift"),
                ],
                default="MANUAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shiftchangerequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftchangerequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftchangerequest",
            name="swap_shift",
            field=models.ForeignKey(
                blank=True,
                help_text="The colleague's shift being swapped in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.shift",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="auto_confirm_offers",
            field=models.BooleanField(
                default=True,
                help_text="First eligible casual to accept an offered shift gets it. Off = a manager chooses.",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="cashup_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minutes a shift may end after closing (cash-up)."
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="close_time",
            field=models.TimeField(
                blank=True, help_text="Closing time, for example 21:00.", null=True
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="is_24h",
            field=models.BooleanField(
                default=False,
                help_text="Open 24 hours, every day of the year (guarded buildings).",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="open_days",
            field=models.CharField(
                default="0,1,2,3,4,5,6",
                help_text="Days it operates, Monday=0 ... Sunday=6, comma separated.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="open_time",
            field=models.TimeField(
                blank=True, help_text="Opening time, for example 05:00.", null=True
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="setup_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minutes a shift may start before opening (set-up).",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("GARAGE", "Garage"),
                    ("BUILDING", "Guarded building"),
                    ("OFFICE", "Office"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="hr.employee",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ABSENT", "Absent"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shiftchangerequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SWAP", "Swap with a colleague"),
                    ("GIVEAWAY", "Give the shift away"),
                    ("CHANGE", "Change the time"),
                    ("OFF", "Ask to be taken off"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shiftchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("AWAITING_COLLEAGUE", "Awaiting colleague"),
                    ("AWAITING_MANAGER", "Awaiting manager"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_flags",
                        to="hr.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_flags",
                        to="hr.employee",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="hr.flag",
                    ),
                ),
            ],
            options={
                "ordering": ["flag__name"],
            },
        ),
        migrations.CreateModel(
            name="OffDayOwed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worked_on", models.DateField()),
                ("settled_on", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="off_days_owed",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="POS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_terminals",
                        to="hr.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS terminal",
                "ordering": ["site", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "continuous_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Must be covered without a gap (small garage attendant, guard posts).",
                    ),
                ),
                (
                    "fair_share",
                    models.BooleanField(
                        default=False,
                        help_text="Duty shared fairly among eligible staff (e.g. small garage).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_flags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="hr.flag"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="hr.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "name"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="hr.post",
            ),
        ),
        migrations.CreateModel(
            name="RequiredHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("hours_30_31", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "hours_february",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_overrides",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Replaced"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="hr.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="roster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="hr.roster",
            ),
        ),
        migrations.CreateModel(
            name="RosterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekend_team",
                    models.CharField(
                        blank=True,
                        help_text="A or B for people on an alternating weekend rotation.",
                        max_length=1,
                    ),
                ),
                (
                    "casual_pay_basis",
                    models.CharField(
                        choices=[
                            ("SHIFT", "Per shift"),
                            ("HOUR", "Per hour"),
                            ("DAY", "Per day"),
                        ],
                        default="SHIFT",
                        max_length=5,
                    ),
                ),
                (
                    "casual_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weekly_hours_cap",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "casual_priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower is offered shifts first (default order is fewest hours this month).",
                    ),
                ),
                ("sms_number", models.CharField(blank=True, max_length=30)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_profile",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_consecutive_days", models.PositiveSmallIntegerField(default=6)),
                (
                    "min_rest_hours",
                    models.DecimalField(decimal_places=1, default=12, max_digits=4),
                ),
                (
                    "weekly_rest_hours",
                    models.DecimalField(decimal_places=1, default=36, max_digits=4),
                ),
                (
                    "max_week_hours",
                    models.DecimalField(decimal_places=1, default=45, max_digits=4),
                ),
                (
                    "max_overtime_hours",
                    models.DecimalField(decimal_places=1, default=10, max_digits=4),
                ),
                ("max_night_run", models.PositiveSmallIntegerField(default=5)),
                ("min_off_days_per_week", models.PositiveSmallIntegerField(default=1)),
                (
                    "tolerance_hours",
                    models.DecimalField(decimal_places=1, default=4, max_digits=4),
                ),
                ("leave_counts_toward_hours", models.BooleanField(default=True)),
                ("leave_counts_as_off_day", models.BooleanField(default=False)),
                (
                    "min_notice_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Shift change requests must be made this many hours before the shift.",
                    ),
                ),
                (
                    "swap_auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="A swap between two eligible people is approved without a manager.",
                    ),
                ),
                ("request_expiry_hours", models.PositiveSmallIntegerField(default=48)),
                (
                    "month_basis",
                    models.CharField(
                        choices=[
                            ("CALENDAR", "Calendar month"),
                            ("PAY_PERIOD", "Pay period"),
                        ],
                        default="CALENDAR",
                        max_length=10,
                    ),
                ),
                (
                    "pay_period_start_day",
                    models.PositiveSmallIntegerField(
                        default=26,
                        help_text="If pay period: the day of the month a period starts (26 = 26th to 25th).",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_settings",
                        to="hr.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField()),
                ("reason", models.CharField(blank=True, max_length=250)),
                ("snapshot", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hr.roster",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="RuleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=30)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("reason", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="hr.roster",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides",
                        to="hr.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "off_day_owed",
                    models.BooleanField(
                        default=False,
                        help_text="SC-9: the replacement worked a required off-day, which is owed back.",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_absences",
                        to="hr.employee",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="hr.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CASUAL", "Casual call-out"),
                            ("EMERGENCY", "Emergency cover"),
                        ],
                        default="CASUAL",
                        max_length=10,
                    ),
                ),
                ("urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("CONFIRMED", "Confirmed"),
                            ("LOST", "Filled by someone else"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OFFERED",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_offers",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="hr.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "day_types",
                    models.CharField(
                        default="WEEKDAY,SAT,SUN,HOLIDAY",
                        help_text="Comma separated: WEEKDAY, SAT, SUN, HOLIDAY.",
                        max_length=40,
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "paid_hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                (
                    "break_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None (default): straight through"),
                            ("UNPAID", "Unpaid lunch (added to the end)"),
                            ("PAID", "Paid lunch (on duty, included)"),
                        ],
                        default="NONE",
                        max_length=6,
                    ),
                ),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "break_window",
                    models.CharField(
                        blank=True,
                        help_text="Preferred lunch window, e.g. 11:00-13:00.",
                        max_length=40,
                    ),
                ),
                (
                    "paid_rest_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Short paid tea breaks: do not change paid hours.",
                    ),
                ),
                ("pay_night", models.BooleanField(default=False)),
                ("pay_sunday", models.BooleanField(default=False)),
                ("pay_holiday", models.BooleanField(default=False)),
                ("pay_weekend", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "compliance_basis",
                    models.CharField(
                        blank=True,
                        help_text="Required when a shift over 5 hours has no meal interval: the written agreement or council rule.",
                        max_length=250,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "compliance_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="hr.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="OpenPOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("WEEKDAY", "Weekday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                            ("HOLIDAY", "Public holiday"),
                        ],
                        max_length=8,
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(default=1)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_pos",
                        to="hr.shifttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_types",
                    models.CharField(default="WEEKDAY,SAT,SUN,HOLIDAY", max_length=40),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed"),
                            ("RANGE", "Range (minimum, target, maximum)"),
                            ("PER_POS", "One per open POS"),
                            ("PER_BUILDING", "Per building"),
                        ],
                        default="FIXED",
                        max_length=12,
                    ),
                ),
                ("minimum", models.PositiveSmallIntegerField(default=1)),
                ("target", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("per_unit", models.PositiveSmallIntegerField(default=1)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher is filled first when there are not enough people (DR-5).",
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_rules",
                        to="hr.site",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_rules",
                        to="hr.post",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_rules",
                        to="hr.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "template", "post"],
            },
        ),
        migrations.CreateModel(
            name="DemandOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("minimum", models.PositiveSmallIntegerField()),
                ("target", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=150)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_overrides",
                        to="hr.site",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.post",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.shifttemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shift",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="hr.shifttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["date", "employee"], name="hr_shift_date_cda51e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["roster", "date"], name="hr_shift_roster__00efd4_idx"
            ),
        ),
        migrations.AddField(
            model_name="siteapproval",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_approvals",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="siteapproval",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty = any post at the site.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="hr.post",
            ),
        ),
        migrations.AddField(
            model_name="siteapproval",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="hr.site",
            ),
        ),
        migrations.AddField(
            model_name="staffgroup",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_groups",
                to="hr.company",
            ),
        ),
        migrations.AddField(
            model_name="rosterprofile",
            name="staff_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="hr.staffgroup",
            ),
        ),
        migrations.AddField(
            model_name="requiredhours",
            name="staff_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hours_history",
                to="hr.staffgroup",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="alt_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Also accepted, e.g. a trained cashier in an attendant slot.",
                related_name="alt_posts",
                to="hr.staffgroup",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="staff_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who may fill it. Empty = anyone.",
                related_name="posts",
                to="hr.staffgroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flag",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="shiftoffer",
            unique_together={("shift", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="openpos",
            unique_together={("template", "day_type")},
        ),
        migrations.AlterUniqueTogether(
            name="siteapproval",
            unique_together={("employee", "site", "post")},
        ),
        migrations.AlterUniqueTogether(
            name="staffgroup",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("site", "name")},
        ),
    ]
