# Generated by Django 5.1.7 on 2026-09-20 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_roster_full"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="freed_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Approved leave freed this slot; it returns to them if the leave is cancelled.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Managers who see and edit this site's roster (MR-8).",
                related_name="managed_sites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffgroup",
            name="pattern_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.post",
            ),
        ),
        migrations.AddField(
            model_name="staffgroup",
            name="pattern_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Pattern groups: where they work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.site",
            ),
        ),
        migrations.AddField(
            model_name="staffgroup",
            name="weekday_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Weekday office shift.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="staffgroup",
            name="weekend_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Weekend duty shift (leave empty for none).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.shifttemplate",
            ),
        ),
    ]
