# Generated by Django 5.1.7 on 2026-09-20 08:04

import HR.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_roster_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="role",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("LINE_MANAGER", "Line Manager"),
                    ("HR_ADMIN", "HR Admin"),
                    ("PAYROLL_ADMIN", "Payroll Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                    ("SENIOR_MANAGER", "Senior Management"),
                    ("ADVANCE_PAYER", "Advance Payer"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("LINE_MANAGER", "Line Manager"),
                    ("HR_ADMIN", "HR Admin"),
                    ("PAYROLL_ADMIN", "Payroll Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                    ("SENIOR_MANAGER", "Senior Management"),
                    ("ADVANCE_PAYER", "Advance Payer"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="key",
            field=models.CharField(
                choices=[
                    ("leave", "Leave request"),
                    ("change_standard", "Profile change"),
                    ("change_banking", "Banking change"),
                    ("payrun_input", "Payrun input"),
                    ("document_request", "Document request"),
                    ("shift_change", "Shift change"),
                    ("salary_change", "Salary change"),
                    ("salary_change_large", "Large salary increase"),
                    ("advance_small", "Advance (manager tier)"),
                    ("advance_large", "Advance (senior tier)"),
                    ("advance_emergency", "Emergency advance"),
                    ("advance_writeoff", "Advance write-off"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AdjustmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(db_index=True, max_length=120)),
                ("period_label", models.CharField(max_length=40)),
                ("original_date", models.DateField()),
                ("difference", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for finance"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Declined"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "recon_expense_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Advance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reason", models.CharField(max_length=250)),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("recovery_payruns", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("AWAITING_APPROVAL", "Awaiting approval"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("PAID", "Paid"),
                            ("RECOVERING", "Recovering"),
                            ("SETTLED", "Settled"),
                            ("WRITTEN_OFF", "Written off"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=18,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("emergency", models.BooleanField(default=False)),
                ("emergency_reason", models.CharField(blank=True, max_length=300)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "final_pay_agreed",
                    models.BooleanField(
                        default=False,
                        help_text="Employee agreed the balance may come off final pay (RC-6).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when a manager, HR or supervisor captured it at the counter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvanceConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CODE", "One-time code"),
                            ("SIGNATURE", "Signed on screen"),
                            ("FINAL_PAY", "Final pay deduction"),
                        ],
                        max_length=10,
                    ),
                ),
                ("code_hash", models.CharField(blank=True, max_length=64)),
                ("code_expires", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_name", models.CharField(blank=True, max_length=150)),
                ("device", models.CharField(blank=True, max_length=250)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agreement_copy", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="hr.advance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Paid out"),
                            ("DEDUCTION", "Payrun deduction"),
                            ("REPAYMENT", "Repayment"),
                            ("WRITE_OFF", "Write-off"),
                            ("FEE", "Fee"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("receipt_number", models.CharField(blank=True, max_length=30)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="hr.advance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AdvancePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH_TILL", "Cash from a till"),
                            ("PETTY_CASH", "Petty cash"),
                            ("TRANSFER", "Electronic transfer"),
                            ("WITH_PAYRUN", "Paid with the next payrun"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "shift_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reconciliation shift (till) the cash came from.",
                        null=True,
                    ),
                ),
                ("petty_cash_id", models.PositiveIntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("receipt_number", models.CharField(blank=True, max_length=30)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recon_expense_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The reconciliation record this created.",
                        null=True,
                    ),
                ),
                (
                    "overlap_note",
                    models.CharField(
                        blank=True,
                        help_text="Set when a small-business setting allowed one person in two roles.",
                        max_length=200,
                    ),
                ),
                (
                    "advance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="hr.advance",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                (
                    "casual_only_against_shifts_worked",
                    models.BooleanField(default=True),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed maximum in rand. Empty = no fixed cap.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_percent_of_earned",
                    models.DecimalField(
                        decimal_places=1,
                        default=50,
                        help_text="Maximum as a percentage of pay earned to date this month.",
                        max_digits=5,
                    ),
                ),
                ("open_advances", models.PositiveSmallIntegerField(default=1)),
                ("min_days_between", models.PositiveSmallIntegerField(default=0)),
                ("min_months_service", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_unpaid_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Not eligible while a balance above this is unpaid.",
                        max_digits=10,
                    ),
                ),
                ("block_on_final_warning", models.BooleanField(default=True)),
                (
                    "recovery_max_payruns",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Longest recovery period, in payruns."
                    ),
                ),
                (
                    "max_recovery_percent_of_pay",
                    models.DecimalField(
                        decimal_places=1,
                        default=50,
                        help_text="No payrun may recover more than this share of the person's pay.",
                        max_digits=5,
                    ),
                ),
                (
                    "tier1_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Up to this amount the line manager approves; above it senior management does.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default none. Shown to the employee before they confirm.",
                        max_digits=5,
                    ),
                ),
                (
                    "staff_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_policy",
                        to="hr.staffgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvanceWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoffs",
                        to="hr.advance",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HRSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_sync_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Go-live switch. Until it is on, nothing in the reconciliation system is changed or locked; the first-load report shows what would change.",
                    ),
                ),
                (
                    "post_advances_to_reconciliation",
                    models.BooleanField(
                        default=True,
                        help_text="Record advances paid and repaid in the reconciliation cash records at once.",
                    ),
                ),
                (
                    "sync_amount_basis",
                    models.CharField(
                        choices=[
                            ("GROSS", "Gross pay"),
                            ("NET", "Net pay paid out"),
                            ("COST", "Cost to company"),
                        ],
                        default="GROSS",
                        max_length=6,
                    ),
                ),
                (
                    "salaries_category",
                    models.CharField(default="Salaries", max_length=100),
                ),
                (
                    "advance_category",
                    models.CharField(default="Salary advance", max_length=100),
                ),
                (
                    "writeoff_category",
                    models.CharField(
                        default="Salary advance write-off", max_length=100
                    ),
                ),
                (
                    "books_closed_through",
                    models.DateField(
                        blank=True,
                        help_text="Finance sets this: the last date of the closed accounting period. The sync never changes closed figures; it proposes an adjustment.",
                        null=True,
                    ),
                ),
                (
                    "increase_needs_senior_pct",
                    models.DecimalField(
                        decimal_places=1,
                        default=10,
                        help_text="A salary increase above this percentage also needs senior management approval.",
                        max_digits=5,
                    ),
                ),
                (
                    "allow_role_overlap",
                    models.BooleanField(
                        default=False,
                        help_text="Small business setting: one person may capture, approve or pay the same advance. Every overlap is recorded.",
                    ),
                ),
                (
                    "unpaid_approved_flag_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="An approved advance not paid after this many days is flagged.",
                    ),
                ),
                ("code_valid_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "agreement_text",
                    models.TextField(
                        default="I ask for a salary advance of the amount shown and I agree that it is deducted from my pay as scheduled, and from my final pay if I leave before it is repaid."
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_settings",
                        to="hr.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrunRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("LOCKED", "Locked")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run",
                        to="hr.payperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoverySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("DEDUCTED", "Deducted"),
                            ("CARRIED", "Carried to next payrun"),
                        ],
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                (
                    "deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="hr.advance",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["advance", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly salary"),
                            ("WEEKLY", "Weekly wage"),
                            ("HOURLY", "Hourly rate"),
                            ("SHIFT", "Per-shift rate"),
                        ],
                        default="MONTHLY",
                        max_length=8,
                    ),
                ),
                ("amount", HR.fields.EncryptedDecimalField()),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("FORTNIGHTLY", "Fortnightly"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("NA", "Not applicable"),
                            ("PENDING", "Pending"),
                            ("SYNCED", "Synced"),
                            ("FAILED", "Failed"),
                            ("UNMATCHED", "Not matched"),
                        ],
                        default="NA",
                        max_length=10,
                    ),
                ),
                ("sync_note", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.salaryrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ALLOWANCE", "Allowance"),
                            ("DEDUCTION", "Deduction"),
                        ],
                        default="ALLOWANCE",
                        max_length=10,
                    ),
                ),
                ("amount", HR.fields.EncryptedDecimalField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hr.salaryrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched to a reconciliation person"),
                            (
                                "NO_COUNTERPART",
                                "No reconciliation counterpart (chosen by an administrator)",
                            ),
                        ],
                        default="MATCHED",
                        max_length=15,
                    ),
                ),
                (
                    "recon_ref",
                    models.CharField(
                        blank=True,
                        help_text="For example the cashier's employee number in the reconciliation system.",
                        max_length=100,
                    ),
                ),
                (
                    "matched_by",
                    models.CharField(default="employee number", max_length=30),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_link",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("source_key", models.CharField(db_index=True, max_length=120)),
                ("target", models.CharField(blank=True, max_length=60)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("old_value", models.CharField(blank=True, max_length=60)),
                ("new_value", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Done"),
                            ("NOCHANGE", "No change"),
                            ("FAILED", "Failed"),
                            ("UNMATCHED", "Not matched"),
                            ("ADJUSTMENT", "Adjustment proposed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrunLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross", HR.fields.EncryptedDecimalField()),
                (
                    "other_deductions",
                    HR.fields.EncryptedDecimalField(default=Decimal("0")),
                ),
                (
                    "advance_recovery",
                    HR.fields.EncryptedDecimalField(default=Decimal("0")),
                ),
                ("net", HR.fields.EncryptedDecimalField()),
                (
                    "company_cost",
                    HR.fields.EncryptedDecimalField(blank=True, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrun_lines",
                        to="hr.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hr.payrunrun",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__surname"],
                "unique_together": {("run", "employee")},
            },
        ),
    ]
