# Generated by Django 4.2 on 2026-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_salary_advances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrsettings",
            name="post_advances_to_reconciliation",
            field=models.BooleanField(
                default=False,
                help_text="Record advances paid and repaid in the reconciliation cash records at once.",
            ),
        ),
    ]
