from django.urls import path

from .views import pay, security, reports, relations, roster, payrun, documents, leave, manage, people, portal

app_name = 'hr'

urlpatterns = [
    path('logout/', security.logout_view, name='logout'),
    # ---- Employee portal (client side) ----
    path('', portal.home, name='portal_home'),
    path('photo/', portal.upload_photo, name='portal_photo'),
    path('reveal/', portal.reveal_sensitive, name='portal_reveal'),
    path('notifications/', portal.notifications, name='portal_notifications'),
    path('notifications/read-all/', portal.notifications_read_all, name='portal_notifications_read_all'),
    path('notifications/<int:pk>/open/', portal.notification_open, name='portal_notification_open'),
    path('soon/<slug:module>/', portal.coming_soon, name='portal_coming_soon'),
    path('delegations/', portal.delegations, name='portal_delegations'),

    path('biographical/', people.biographical, name='biographical'),
    path('biographical/<slug:section>/edit/', people.change_edit, name='change_edit'),
    path('biographical/<slug:section>/<int:pk>/edit/', people.change_edit, name='change_edit_item'),
    path('biographical/<slug:section>/<int:pk>/remove/', people.change_remove, name='change_remove'),
    path('biographical/change/<int:pk>/withdraw/', people.change_withdraw, name='change_withdraw'),
    path('payslips/', people.payslips, name='payslips'),
    path('tax-certificates/', people.tax_certificates, name='tax_certificates'),
    path('tax-certificates/<int:pk>/correction/', people.tax_correction, name='tax_correction'),
    path('file/<str:token>/', people.file_open, name='file_open'),
    path('manage/payroll/', people.batches, name='manage_batches'),
    path('manage/payroll/periods/', people.periods, name='manage_periods'),
    path('manage/payroll/upload/<slug:kind>/', people.batch_new, name='manage_batch_new'),
    path('manage/payroll/<int:pk>/', people.batch_detail, name='manage_batch'),
    path('manage/payroll/<int:pk>/action/', people.batch_action, name='manage_batch_action'),
    path('manage/payroll/row/<slug:kind>/<int:pk>/assign/', people.row_assign, name='manage_row_assign'),
    path('manage/payroll/row/<slug:kind>/<int:pk>/withdraw/', people.row_withdraw, name='manage_row_withdraw'),

    path('documents/', documents.documents, name='documents'),
    path('documents/<int:pk>/sign/', documents.doc_sign, name='doc_sign'),
    path('documents/policy/<int:pk>/ack/', documents.policy_ack, name='policy_ack'),
    path('documents/request/', documents.request_letter, name='request_letter'),
    path('manage/documents/', documents.manage_documents, name='manage_documents'),
    path('manage/documents/upload/', documents.doc_upload, name='manage_doc_upload'),
    path('manage/documents/<int:pk>/withdraw/', documents.doc_withdraw, name='manage_doc_withdraw'),
    path('manage/documents/request/<int:pk>/fulfil/', documents.request_fulfil, name='manage_request_fulfil'),
    path('manage/documents/policy/', documents.policy_publish, name='manage_policy_publish'),
    path('manage/documents/policy/<int:pk>/acks/', documents.policy_acks, name='manage_policy_acks'),
    path('payrun-input/', payrun.payrun_input, name='payrun_input'),
    path('payrun-input/<int:pk>/withdraw/', payrun.payrun_withdraw, name='payrun_withdraw'),
    path('manage/payroll/inputs/', payrun.payrun_admin, name='manage_payrun'),
    path('manage/payroll/inputs/<int:pk>/cutoff/', payrun.payrun_cutoff, name='manage_payrun_cutoff'),
    path('manage/payroll/inputs/<int:pk>/export/', payrun.payrun_export, name='manage_payrun_export'),
    path('roster/', roster.roster, name='roster'),
    path('roster/availability/', roster.availability_save, name='availability_save'),
    path('roster/shift/<int:pk>/request/', roster.shift_request, name='shift_request'),
    path('roster/request/<int:pk>/respond/', roster.request_respond, name='request_respond'),
    path('roster/request/<int:pk>/cancel/', roster.request_cancel, name='request_cancel'),
    path('roster/offers/', roster.offers, name='roster_offers'),
    path('roster/offers/<int:pk>/respond/', roster.offer_respond, name='offer_respond'),
    path('roster/feed/<str:token>.ics', roster.calendar_feed, name='roster_feed'),
    path('manage/roster/', roster.manage_roster, name='manage_roster'),
    path('manage/roster/generate/', roster.roster_generate, name='manage_roster_generate'),
    path('manage/roster/<int:pk>/', roster.manage_roster_detail, name='manage_roster_detail'),
    path('manage/roster/<int:pk>/regenerate/', roster.roster_regenerate, name='manage_roster_regenerate'),
    path('manage/roster/<int:pk>/publish/', roster.roster_publish, name='manage_roster_publish'),
    path('manage/roster/<int:pk>/export/', roster.roster_export, name='manage_roster_export'),
    path('manage/roster/<int:pk>/print/', roster.roster_print, name='manage_roster_print'),
    path('manage/roster/<int:pk>/add-shift/', roster.shift_add, name='manage_shift_add'),
    path('manage/roster/shift/<int:pk>/', roster.shift_edit, name='manage_shift_edit'),
    path('manage/roster/shift/<int:pk>/assign/', roster.shift_assign, name='manage_shift_assign'),
    path('manage/roster/shift/<int:pk>/action/', roster.shift_action, name='manage_shift_action'),
    path('manage/roster/requests/', roster.manage_requests, name='manage_requests'),
    path('manage/roster/requests/<int:pk>/decide/', roster.request_decide, name='manage_request_decide'),
    path('manage/roster/offers/<int:pk>/confirm/', roster.offer_confirm, name='manage_offer_confirm'),
    path('manage/roster/reports/<slug:kind>/', roster.roster_reports, name='manage_roster_reports'),
    path('manage/roster/flags/', roster.roster_flags, name='manage_roster_flags'),
    path('manage/roster/setup/', roster.roster_setup, name='manage_roster_setup'),
    path('manage/roster/copy-site/', roster.roster_copy_site, name='manage_roster_copy_site'),
    path('manage/roster/import/', roster.roster_import, name='manage_roster_import'),
    path('relations/', relations.relations, name='relations'),
    path('relations/grievance/', relations.grievance_raise, name='grievance_raise'),
    path('relations/warning/<int:pk>/ack/', relations.warning_ack, name='warning_ack'),
    path('relations/warning/<int:pk>/appeal/', relations.warning_appeal, name='warning_appeal'),
    path('relations/hearing/<int:pk>/ack/', relations.hearing_ack, name='hearing_ack'),
    path('manage/relations/', relations.manage_relations, name='manage_relations'),
    path('manage/relations/grievance/<int:pk>/', relations.manage_grievance, name='manage_grievance'),
    path('manage/relations/grievance/<int:pk>/update/', relations.grievance_update, name='manage_grievance_update'),
    path('manage/relations/warning/', relations.warning_issue, name='manage_warning_issue'),
    path('manage/relations/warning/<int:pk>/decide/', relations.warning_decide, name='manage_warning_decide'),
    path('manage/relations/hearing/', relations.hearing_invite, name='manage_hearing_invite'),
    path('manage/reports/', reports.reports, name='manage_reports'),
    path('manage/reports/headcount.csv', reports.headcount_csv, name='manage_headcount_csv'),
    path('security/password/', security.password_change, name='password_change'),
    path('advances/', pay.advances, name='advances'),
    path('advances/<int:pk>/confirm/', pay.advance_confirm, name='advance_confirm'),
    path('advances/<int:pk>/resend/', pay.advance_resend, name='advance_resend'),
    path('advances/<int:pk>/cancel/', pay.advance_cancel, name='advance_cancel'),
    path('manage/advances/', pay.advance_list, name='manage_advances'),
    path('manage/advances/capture/', pay.advance_capture, name='manage_advance_capture'),
    path('manage/advances/<int:pk>/', pay.advance_detail, name='manage_advance_detail'),
    path('manage/advances/<int:pk>/action/', pay.advance_action, name='manage_advance_action'),
    path('manage/advances/<int:pk>/receipt/', pay.advance_receipt, name='manage_advance_receipt'),
    path('manage/salaries/', pay.salaries, name='manage_salaries'),
    path('manage/salaries/import/', pay.salary_import, name='manage_salary_import'),
    path('manage/salaries/<int:pk>/reveal/', pay.salary_reveal, name='manage_salary_reveal'),
    path('manage/salaries/<int:pk>/history/', pay.salary_history, name='manage_salary_history'),
    path('manage/salaries/<int:pk>/change/', pay.salary_capture, name='manage_salary_capture'),
    path('manage/payruns/', pay.runs, name='manage_runs'),
    path('manage/payruns/<int:pk>/', pay.run_detail, name='manage_run'),
    path('manage/sync/', pay.sync_console, name='manage_sync'),
    path('manage/pay-reports/<slug:kind>/', pay.pay_reports, name='manage_pay_reports'),
    path('leave/', leave.leave_home, name='leave_home'),
    path('leave/apply/', leave.leave_apply, name='leave_apply'),
    path('leave/preview/', leave.leave_preview, name='leave_preview'),
    path('leave/calendar/', leave.leave_calendar, name='leave_calendar'),
    path('leave/statement/', leave.leave_statement, name='leave_statement'),
    path('leave/<int:pk>/', leave.leave_detail, name='leave_detail'),
    path('leave/<int:pk>/cancel/', leave.leave_cancel, name='leave_cancel'),

    # ---- Admin site (HR, payroll, managers) ----
    path('manage/', manage.dashboard, name='manage_home'),
    path('manage/approvals/', manage.approvals, name='manage_approvals'),
    path('manage/approvals/<int:step_id>/decide/', manage.approval_decide, name='manage_approval_decide'),
    path('manage/team/', manage.team, name='manage_team'),
    path('manage/company/<int:pk>/switch/', manage.switch_company, name='manage_switch_company'),

    path('manage/employees/', manage.employees, name='manage_employees'),
    path('manage/employees/new/', manage.employee_edit, name='manage_employee_new'),
    path('manage/employees/<int:pk>/', manage.employee_detail, name='manage_employee'),
    path('manage/employees/<int:pk>/edit/', manage.employee_edit, name='manage_employee_edit'),
    path('manage/employees/<int:pk>/record/', manage.employee_add_record, name='manage_employee_record'),

    path('manage/roles/', manage.roles, name='manage_roles'),
    path('manage/roles/<int:pk>/delete/', manage.role_delete, name='manage_role_delete'),
    path('manage/audit/', manage.audit_log, name='manage_audit'),
    path('manage/audit/export/', manage.audit_export, name='manage_audit_export'),

    path('manage/leave/requests/', manage.leave_requests, name='manage_leave_requests'),
    path('manage/leave/capture/', manage.leave_capture, name='manage_leave_capture'),
    path('manage/leave/adjust/', manage.leave_adjust, name='manage_leave_adjust'),
    path('manage/leave/accruals/', manage.leave_run_accruals, name='manage_leave_accruals'),
    path('manage/leave/balances/', manage.leave_balances, name='manage_leave_balances'),

    # generic lists for organisation and settings (companies, sites, leave types...)
    path('manage/setup/<slug:key>/', manage.crud_list, name='manage_crud'),
    path('manage/setup/<slug:key>/new/', manage.crud_edit, name='manage_crud_new'),
    path('manage/setup/<slug:key>/<int:pk>/', manage.crud_edit, name='manage_crud_edit'),
    path('manage/setup/<slug:key>/<int:pk>/delete/', manage.crud_delete, name='manage_crud_delete'),
]
